name: Build PCF Solution
on:
  workflow_dispatch:
  push: { branches: [ main, master ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '18' }
      - run: npm ci || npm i
      - run: npx pcf-scripts build
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }
      - uses: microsoft/powerplatform-actions/actions-install@v1
      - name: Locate pac and add to PATH
        id: addpac
        shell: bash
        run: |
          DIR="$(dirname "$(find /tmp -type f -name pac 2>/dev/null | head -n1)")"
          echo "Found pac in: $DIR"
          if [ -z "$DIR" ]; then echo "pac not found"; exit 1; fi
          echo "$DIR" >> "$GITHUB_PATH"
          which pac
          pac --version
      - name: Init solution
        run: |
          pac solution init --publisher-name "Hatch" --publisher-prefix "hch" --outputDirectory solution
          pac solution add-reference --path . --solution-unique-name hch_ImageResizerPCF --outputDirectory solution
      - name: Build solution (Both)
        run: pac solution build --outputDirectory out --packageType Both --zipFileName ImageResizerPCF
      - uses: actions/upload-artifact@v4
        with: { name: ImageResizerPCF_Solution_Zips, path: out/*.zip }
