name: Build PCF Solution
on:
  workflow_dispatch:
  push: { branches: [ main, master ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: '18' }

      - name: Install dev deps
        run: npm install

      - name: Sanity check repo layout
        run: |
          ls -la
          test -f ControlManifest.Input.xml
          test -f index.ts
          test -f Control.css
          test -f strings/ControlManifest.resx

      - name: Build PCF control
        run: npx pcf-scripts build

      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      # Find pac and expose it as $PAC for later steps
      - name: Locate pac and export PAC env
        id: addpac
        shell: bash
        run: |
          DIR="$(dirname "$(find /tmp -type f -name pac 2>/dev/null | head -n1)")"
          echo "Found pac in: $DIR"
          if [ -z "$DIR" ]; then
            echo "pac not found"; exit 1
          fi
          echo "PAC=$DIR/pac" >> "$GITHUB_ENV"
          "$DIR/pac" help

      - name: Init solution
        run: |
          "$PAC" solution init --publisher-name "Hatch" --publisher-prefix "hch" --outputDirectory solution
          "$PAC" solution add-reference --path . --solution-unique-name hch_ImageResizerPCF --outputDirectory solution

      - name: Build solution (Both)
        run: |
          "$PAC" solution build --outputDirectory out --packageType Both --zipFileName ImageResizerPCF

      - uses: actions/upload-artifact@v4
        with:
          name: ImageResizerPCF_Solution_Zips
          path: out/*.zip
