name: Build PCF Solution

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dev deps
        run: npm ci || npm i

      - name: Build PCF control
        run: npx pcf-scripts build

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # ✅ Official installer – avoids the dotnet tool packaging issue
      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      # Create a solution folder, add the project, and build Managed/Unmanaged zips
      - name: Init solution
        run: |
          pac solution init --publisher-name "Hatch" --publisher-prefix "hch" --outputDirectory solution
          pac solution add-reference --path . --solution-unique-name hch_ImageResizerPCF --outputDirectory solution

      - name: Build solution (Both)
        run: pac solution build --outputDirectory out --packageType Both --zipFileName ImageResizerPCF

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ImageResizerPCF_Solution_Zips
          path: out/*.zip
